### PR TITLE
[do-not-merge] [review-request] Nubis bash library

### PR DESCRIPTION
**Pull request by limed**
This is a simple library for regular patterns that we use in nubis, there isn't any plumbing to get it installed in our instances yet until it gets reviewed by @gozer and @tinnightcap 

This PR also fixes issue #67

### CODE REVIEW

**Comment by tinnightcap** [comment]
I like this idea in general. I only have one or two minor questions about the code, it looks good. I need a little time to think about this approach in general and perhaps have a discussion around it with all of us.

My technical questions are:
 1. Should we rename the migrate variable (seems strange parlance)?
 1. Is jq actually a requirement for all of our base images (and should it be)?

**Comment by limed** [comment]
To answer some of your questions

> 1. Should we rename the migrate variable (seems strange parlance)?

I think there is a issue open already for this? nubisproject/nubis-stacks#83 I don't know the historical reasoning behind this variable so if its not needed I'm ok with removing

> 2. Is jq actually a requirement for all of our base images (and should it be)?

jq is actually installed in base at the moment and and its also one of the ways we get the `REGION` variable.
 ```
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)
```
There are other ways we can get region is jq is not installed by default, however I believe that means we need to change a bunch of code elsewhere where we get the AWS region through this method.

**Comment by gozer** [comment]
I am the one that included jq in the base images a long time ago. One reason was to *not* grep/awk at JSON, but the main motivator was because I was planning to change user_data into a JSON blob, so I anticipated it's need there.

**Comment by limed** [comment]
Getting a feel for this PR, do I get an r+ from folks?

**Comment by tinnightcap** [comment]
r+ :+1:

**Comment by gozer** [comment]
R=gozer, will need to start making use of it in startup scripts next.

Also probably worthwhile to hide some OS differences in there eventually

**Pull request merged**
