### PR TITLE
Create nubis-metadata to access instance user-data

### LINKED ISSUE #115: Create a nubis-metadata tool to hide away the AWS EC2 metadata

### LINKED ISSUE #251: [user-data] Cache user-data locally and provide some convenient way to query it
Doing :

  USER_DATA=$(curl -fqs http://169.254.169.254/latest/user-data)
  eval $USER_DATA

All over the place is starting to feel wrong, why not something like:

$> nubis-lookup region
$> nubis-lookup environment
$> nubis-lookup role

Or something similar, could even be used eventually to make access to the user-data
access-controlled.

### PR DESCRIPTION
**Pull request by gozer**
Usage:

$> eval $(nubis-metadata)

$> nubis-metadata NUBIS_PURPOSE

Fixes #115
Fixes #251

### CODE REVIEW

**Comment by limed** [comment]
Just a point to note: nubis-lib (https://github.com/nubisproject/nubis-base/blob/master/nubis/puppet/files/nubis-lib.sh#L9) already. What is the use case of this? Will be we be using this in shell scripts? or just as a CLI thing?

**Comment by gozer** [comment]
Very good point about nubis-lib, actually. I completely overlooked it, actually.

This was a very old leftover itch I've been meaning to scratch for a long time.

Basically, the idea is to rip out all AWS specific juju out of scripts, where it's currently sprinkled all over the place, and move into as few contained pieces as possible.

My followup work to nubis-metadata would be to convert everything everywhere that uses AWS user-data directly to using it.

This way, we can achieve better encapsulation of that AWS assumptions we litter all over the place.

**Comment by limed** [comment]
I think what we can do here is use nubis-metadata and then create specific functions we need using nubis-metadata in nubis-lib

**Comment by gozer** [comment]
@limed yeah, I like that plan.

In my mind, we need to be clearer about what we do in general. For instance, in some script, I don't need user-data, I am actually asking what project I belong to. Or what region I happen to be running in. Things like that.

I'd much prefer if we ended up eventually with

$> nubis-metadata --region
$> nubis-metadata --project

Things like that.

**Comment by limed** [comment]
r+

**Pull request merged**
